{
  "app_title": "AcquaSmart",
  "login_welcome": "Bienvenue sur AcquaSmart",
  "login_tagline": "La façon intelligente de gérer votre aquarium.",
  "login_with_google": "Se connecter avec Google",
  "login_with_apple": "Se connecter avec Apple",
  "login_with_email": "Continuer avec l'e-mail",
  "dashboard_health_score": "Score de Santé",
  "dashboard_title": "Tableau de bord",
  "inventory_title": "Inventaire du Vivant",
  "inventory_total_value": "Valeur Totale",
  "maintenance_title": "Maintenance Intelligente",
  "trial_ends_in_days": "L'essai se termine dans {{days}} jours",
  "trial_expired_title": "Essai Expiré",
  "trial_expired_message": "Abonnez-vous pour débloquer toutes les fonctionnalités et protéger vos habitants.",
  "subscribe_button": "S'abonner pour {{price}}/mois",
  "settings_title": "Paramètres",
  "language_selection": "Sélectionner la langue",
  "login_label_email": "Nom d'utilisateur ou e-mail",
  "login_label_password": "Mot de passe",
  "login_button_classic": "Connexion",
  "login_signup_prompt": "Vous n'avez pas de compte ?",
  "login_signup_link": "Inscrivez-vous",
  "profile_title": "Profil",
  "logout_button": "Déconnexion",
  "add_tank_title": "Configurez votre Aquarium",
  "add_tank_subtitle": "Entrez les détails principaux pour commencer.",
  "tank_name_label": "Nom de l'aquarium (ex. Salon)",
  "tank_type_freshwater": "Eau douce",
  "tank_type_saltwater": "Eau de mer",
  "tank_type_brackish": "Eau saumâtre",
  "tank_volume_label": "Volume (en litres)",
  "save_tank_button": "Enregistrer et Continuer",
  "log_test_title": "Enregistrer un nouveau test",
  "log_test_button": "Enregistrer les résultats",
  "log_test_button_short": "Enregistrer Test",
  "log_test_temp": "Température",
  "log_test_nitrates": "Nitrates (NO₃)",
  "chart_title": "Historique des valeurs",
  "chart_no_data": "Enregistrez au moins deux tests pour afficher le graphique.",
  "log_temp_title": "Enregistrer la température",
  "log_ph_title": "Enregistrer le pH",
  "log_nitrates_title": "Enregistrer les nitrates",
  "log_history_title": "Historique Récent",
  "reset_history_button": "Réinitialiser l'historique",
  "reset_history_confirm": "Êtes-vous sûr de vouloir supprimer toutes les entrées pour ce paramètre ? Cette action est irréversible."
}
