{
  "app_title": "AcquaSmart",
  "login_welcome": "Bienvenido a AcquaSmart",
  "login_tagline": "La forma inteligente de gestionar tu acuario.",
  "login_with_google": "Iniciar sesión con Google",
  "login_with_apple": "Iniciar sesión con Apple",
  "login_with_email": "Continuar con Email",
  "dashboard_health_score": "Puntuación de Salud",
  "dashboard_title": "Panel de Control",
  "inventory_title": "Inventario Vivo",
  "inventory_total_value": "Valor Total",
  "maintenance_title": "Mantenimiento Inteligente",
  "trial_ends_in_days": "La prueba termina en {{days}} días",
  "trial_expired_title": "Prueba Expirada",
  "trial_expired_message": "Suscríbete para desbloquear todas las funciones y proteger a tus habitantes.",
  "subscribe_button": "Suscríbete por {{price}}/mes",
  "settings_title": "Ajustes",
  "language_selection": "Seleccionar Idioma",
  "login_label_email": "Nombre de usuario o correo electrónico",
  "login_label_password": "Contraseña",
  "login_button_classic": "Iniciar sesión",
  "login_signup_prompt": "¿No tienes una cuenta?",
  "login_signup_link": "Regístrate",
  "profile_title": "Perfil",
  "logout_button": "Cerrar sesión",
  "add_tank_title": "Configura tu Acuario",
  "add_tank_subtitle": "Introduce los detalles principales para empezar.",
  "tank_name_label": "Nombre del acuario (ej. Salón)",
  "tank_type_freshwater": "Agua dulce",
  "tank_type_saltwater": "Agua salada",
  "tank_type_brackish": "Agua salobre",
  "tank_volume_label": "Volumen (en litros)",
  "save_tank_button": "Guardar y Continuar",
  "log_test_title": "Registrar Nuevo Test",
  "log_test_button": "Guardar Resultados",
  "log_test_button_short": "Registrar Test",
  "log_test_temp": "Temperatura",
  "log_test_nitrates": "Nitratos (NO₃)",
  "chart_title": "Historial de Valores",
  "chart_no_data": "Registra al menos dos tests para ver el gráfico.",
  "log_temp_title": "Registrar Temperatura",
  "log_ph_title": "Registrar pH",
  "log_nitrates_title": "Registrar Nitratos"
}
